package main

import (
	"net/http"
	"github.com/labstack/echo/v4"
   "github.com/swaggo/echo-swagger"
 	_ "github.com/swaggo/echo-swagger/example/docs" // docs is generated by Swag CLI, you have to import it.

)

func main() {
	e := echo.New()
   
   // Swagger
   e.GET("/swagger/*", echoSwagger.WrapHandler)

	e.GET("/", func(c echo.Context) error {
		return c.String(http.StatusOK, "Hello, World!")
	})
	e.Logger.Fatal(e.Start(":3100"))
}
