package main

import (
	"github.com/labstack/echo/v4/middleware"
	"github.com/labstack/echo/v4"
	"github.com/swaggo/echo-swagger"
 	_ "github.com/swaggo/echo-swagger/example/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/torreswoo/template-go-echo/handler"
)

func main() {
	e := echo.New()

	// --- Middleware
  // Swagger
  e.GET("/swagger/*", echoSwagger.WrapHandler)
	// Logger
	e.Use(middleware.LoggerWithConfig(middleware.LoggerConfig{
		Skipper: func(ctx echo.Context) bool {
			return false
		},
	}))

	// --- Handler
	e.GET("/", handler.Hello)
	e.GET("/healthz", handler.Health)

	e.Logger.Fatal(e.Start(":3100"))
}
